### ISSUE TITLE
scalariform should format sources in the base directory 

### ISSUE THREAD

**Issue by stewSquared** [sbt/sbt-scalariform#40]
At present, sbt-scalariform does not format any `.scala` files in the project's base directory. It's [totally valid](http://www.scala-sbt.org/0.13/docs/Directories.html) to place source files in the base directory, which means scalariform doesn't actually format every file that sbt compiles, as the docs imply. 

Is this configurable? It stands to reason that my suggestion should be the default behaviour, but at the very least, it should be mentioned in the docs that scalariform will only format files in `src`.

**Comment by fthomas** [comment]
@stewSquared You can configure this by adding the base directory to the `sourceDirectories in (Compile, SbtScalariform.ScalariformKeys.format)` setting.

This should do the trick:
```sbt
sourceDirectories in (Compile, SbtScalariform.ScalariformKeys.format) +=
    baseDirectory.in(LocalRootProject).value
```

**Comment by michaelahlers** [comment]
Maybe add this to the usage notes? (It's useful adding custom source roots as well.)

**Comment by godenji** [comment]
Fixed in 1.8.0 release

**Comment by andrebeat** [comment]
I'm not sure this is intended behavior but this breaks the subproject scoping, i.e. compiling a subproject formats all the files in the whole project.

**Comment by godenji** [comment]
@andrebeat 

> inspect scalariformFormat::sourceDirectories

From top-level projects shows that the project root is added to eligible sources. Subprojects inherit the parent setting, thus the subproject formats the entire project.

Presumably one wants to format *all* sources and not just those in current subproject. Formatted sources are cached so I don't see the current behavior as particularly problematic.

Feel free to open a new issue to track this though, should be a way to exclude the project root from `sourceDirectories` for subprojects.

**Comment by simlei** [comment]
I have problems with this. Currently, my project formats all sources multiple times, leading to heavy overhead. Each subproject's ``scalariformFormat`` in their different scopes have the project root in their ``sourceDirectories`` setting. This just leads to the whole project being crawled for scala sources as many times as there are subprojects. Cahing does nothing as the cache resides in the subproject folders.

It should be noted that in my setup, sbt-scalariform is not configured for the aggregating root project, just for the subprojects. 

IMHO the ``sourceDirectories`` setting should just include the subproject root, not the "real" root. In extension, the current behavior just causes each and every file in a subproject to be formatted - it searches the root recursively. I am not sure this is expected behavior.

For a basic fix (not breaking subproject scopes and forced redundant formatting) it would require to change this line: https://github.com/sbt/sbt-scalariform/blob/3b83dbe29f739ec593769dda19810ba6a3b6e751/src/main/scala/com/typesafe/sbt/SbtScalariform.scala#L102

by replacing ``LocalRootProject`` with ``ThisProject``.

If there is agreement I can make a PR.

For anyone interested in a hotfix, I am currently using this to configure subprojects in the root/build.sbt:

```
lazy val scalariformSettings = scalariformSettingsWithIt(true) ++
	Seq(ScalariformKeys.preferences := baseDirectory(getScalariformPreferences).value) ++
	Seq(sourceDirectories.in(Compile, ScalariformKeys.format) -= baseDirectory.in(LocalRootProject).value) ++
	Seq(sourceDirectories.in(Test, ScalariformKeys.format) -= baseDirectory.in(LocalRootProject).value) ++
	Seq(sourceDirectories.in(IntegrationTest, ScalariformKeys.format) -= baseDirectory.in(LocalRootProject).value)
```
