### ISSUE TITLE
format only one file

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-scalariform#68]
we have a command in `sbt-ensime` that probably makes more sense here. Would you like to copy this command? https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/EnsimeExtrasPlugin.scala#L229-L248

**Comment by godenji** [comment]
> Would you like to copy this command?

Not particularly ;-)

[Scalariform CLI](https://github.com/scala-ide/scalariform/wiki/Command-line-tool) already supports the same behavior. Baking in a task to handle the rare scenario where one would want to format individual sources a la carte seems unwarranted -- Scalariform is *really fast*, blows away `scalac` and `scalafmt`; most users can format their entire application in the time it takes either of the latter to process a few sources.

**Comment by fommil** [comment]
but this is from a warm jvm, with the configuration the user has set in their build, why would you not want this function? Asking everybody to install the CLI and set it up separately (plus extra config for each project, that will diverge from the build's definition) is something everybody can do *today* but are not.

**Comment by godenji** [comment]
Sure, of course having the task built-in to the plugin would be more convenient than using the CLI, I'm more questioning the need for the feature itself.

It's one more thing to maintain (and implement, no longer a copy/paste as of 1.8.0). Unless the task provides a substantial improvement over existing `compile/scalariformFormat` task it doesn't seem worth the trouble. I mean, most of the time your sources are already formatted and cached, micro managing formattable sources seems pointless.

Convince me otherwise (real world use cases) and I'll add it.

**Comment by fommil** [comment]
People are already using this feature in ensime. It is already a desirable feature.

It supports projects that are not using format on compile or for one reason or another (usually because it has gone too long without it) cannot format all the files.

It is testable.

**Comment by aij** [comment]
@godenji Here's a real world use case: We have a largeish project (250k lines of scala across 3k files) with active development across various "feature" branches. We could certainly benefit from an automatic formatter since the team spends way too much time (AKA any at all) bickering over indentation. Reformatting the entire codebase at once seems like a non-starter due to the merge nightmare it would create.

Per-file reformatting would allow us to start using scalariform.

(An even better feature for a later stage of adoption would  be to reformat all files except those that have pending changes on other branches.)

**Comment by fommil** [comment]
we're going to remove this feature from the next release of sbt-ensime. If people still want it, I'll direct them here and maybe they can send you a PR and you can decide then if it makes sense, or if they should create a separate plugin.

**Comment by godenji** [comment]
It's fine to include it here, just over the top busy at the moment. Will look into it (or merge a PR) when I come up for air.

**Comment by fommil** [comment]
:smile: just wait for a PR, if this isn't something you personally want you shouldn't have to spend time on it.

**Comment by fommil** [comment]
The original link no longer contains the code... if anybody is interested, just wind back in the history a few commits.
